### ISSUE TITLE
Can't report AFK in BG's.

### ISSUE THREAD

**Issue by NayooZ** [leatrix/leatrix-maps-wrath#56]
```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'ReportPlayerIsPVPAFK()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ReportPlayerIsPVPAFK'
[string "@Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua"]:189: in function `func'
[string "@FrameXML\UIDropDownMenu.lua"]:944: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

![image](https://user-images.githubusercontent.com/37068647/188272935-08b53d2e-7659-4df1-b5d4-2b5a3caf7be8.png)

**Comment by leatrix** [comment]
If you click the reload button, does the report function work after the reload?

**Comment by NayooZ** [comment]
No it just triggers the stop error again

**Comment by leatrix** [comment]
You are trying to kick someone by right-clicking the player's icon on the world map and choosing kick from the menu.  But it doesn't work.  There isn't anything I can do to fix that as it's caused by an issue with the game code.

A workaround is to target the player, right-click the target frame and choose kick from the menu.  That should work fine.  I know it's not as useful as right-clicking the map but there it is.
