### ISSUE TITLE
Map location not accurate

### ISSUE THREAD

**Issue by Chubbwubb** [leatrix/leatrix-maps-wrath#60]
When looking at the map, the arrow which shows my current player location, is not accurate for where I'm currently at. In the attached screenshot, it shows my cursor out in "dead space" when I'm standing in the war room with all the Battleground NPC's. 

I've disabled all other addons and I still have the issue. I will also mention that the mod worked WONDERFULLY on TBC Classic, but ever since WOTLK Classic dropped and I've updated the mod, I now have this issue.

Any help would be greatly appreciated. If there's anything else that you need me to test, I'm more than happy to do so.

Thank you!

![Leatrix Location Issue](https://user-images.githubusercontent.com/112938823/188599974-68ae98be-d971-4a55-a1f7-0f37499a83f2.JPG)

**Comment by leatrix** [comment]
It looks like you're using an addon which replaces map textures because the world map doesn't look like that.

If all addons are disabled, check your Interface folder to see if you have a folder called WorldMap.  If you have that folder, delete it (or move it somewhere else) then restart your game client (a relog won't be enough, it has to be a full client restart).  The only folder you should have in your Interface folder is AddOns.

**Comment by Chubbwubb** [comment]
Thank you for the quick response and the good tip. I have no idea idea what addon i installed that created that folder but you were 100% correct. I deleted the WorldMap folder and now it's working perfectly.

Thank you so much for the assistance with this, I greatly appreciate it.
