### ISSUE TITLE
Enhance Minimap checkmark disappears after logout

### ISSUE THREAD

**Issue by ericbarr580** [leatrix/leatrix-maps-wrath#69]
Minimap enhancem,ents, specifically square map with consolidated buttons, disappear after logging.  Need to open ltp and reenable minimap enhancements

**Comment by leatrix** [comment]
If you enable settings (by checking boxes) then reload and the boxes you checked are no longer checked, that's usually caused by a conflict with another addon. 
 Disable all other addons and see if that fixes it.  If it does fix it, enable other addons gradually until you find the addon causing the problem.  You can then either disable that addon or let me know the addon name so that I can advise you further.
