### ISSUE TITLE
Conflict with TomTom

### ISSUE THREAD

**Issue by Alium369** [leatrix/leatrix-maps-wrath#71]
Greetings,

There's a conflict with TomTom, where when you right-click a TomTom marker on the map the menu is showing behind the map so it is not visible.  I've looked through settings in both addons and can't find a way to put the menu in the foreground.  This used to work fine until the past few days.

**Comment by leatrix** [comment]
This isn't caused by LTM.  It does this with the default UI map too.  You need to raise this with TomTom.

Until TomTom fixes it, open TomTom.lua with Notepad++ and search for this line:

`self:InitializeDropdown(self.dropdown)`

add this line directly below it:

`self.dropdown:SetFrameStrata("HIGH")`

Save the file, reload your UI and the problem should be solved.

**Comment by Alium369** [comment]
Appreciate it!  I actually raised the issue with them as well at the same time since I wasn’t sure where the problem was, and they already pushed out a fix.

Thank you much for taking the time to look, and even providing a solution.

Jeff
________________________________
